---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: night-sky-postgres
  namespace: night-sky
spec:
  encryptedData:
    password: AgCD7YLZOxTNASWRg5sXgqsReEMf0XDMTGlXa/IkrVRxvqCHiFTnxsq7bzVl9imkn0L7ylpNB0NNQ60CTpYx6FJ6K7jwHCGzATJmZKF0BZWKwtV7aJive6jKRaPZ1cKrtKKPPCW7YZtrzN96a5JLlxqVZm/bHYu//oXGdNTFLFqvjFD0bMkY45G1/v4sbaBHhWzAfuDK5qhLhcCyVUPX7XdBoz5n4U3TjjP5RgMwssL99Ua0VEPVB8wUg90i/mX9Ku0ghziZqhIe0WdeuWkGOJzyyLV2SFdUOWiMExX8EFvODRQ11wTNkOLNx3MhXNaMEHJih8v1Q9Rji+mehgnHdoKJ7mVyzdI/q9B7wpPIOKLqbOXXp2DkC15QVwW8DwcEMuGl97mru5d5p8pIMxqk1qBZSAYei6rDyb+387Jw4vp+lPfDqjXsKQCWdHididMkrq+uIuMAOEYe/2SX3M1efB0poFHUBgVSU2Fgnqdu+OkNdWxrCJpEmP/d6x+CEAiMi607eY/ggYcQ7Yfr357/xHYapBQfbnHJPB4kEf7EdEvoSg/i7z04CxLR4RHbU0qz2tBR1TEEfaDN5q5fgl1N9K9zGJc9y4vWsf5w+9aBMnFbr4dC2Q6sTNgN4qs27tyagQ9Iqkj2wOesGLwr/ihB1ezhrn+KnOK7uElZZ4c6p3eBqLE1ALeT31Xb5JkTwAPiDuNAN7VuPnZfZ0N6DpQ3HFl8rqLTvUoPL5/Lcn+SuJvPcfRQ53kNMPh9Q2dncA==
  template:
    metadata:
      name: night-sky-postgres
      namespace: night-sky
