---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA606lhWHRyNoZpfsajdMfBYCZkskFGb5BLXbBjD+G1xiADi9bPXPyOQBlpD+f6mQf+Q8/i6XH9ulpsF6gh6++kxYp39jm/Il2JedL83N8oPjLR+yxo4jzIfqk2256h+V8px3u++ogVL3EfTA5LQnw9DsfM/UJmrRuARjqkvL1qawbVmjaARI4qakkQ44Df6ggss2DBQZb3OulRlIZAdnc2gBstp0WaV5ICzDGPu713etPxc+l0F1/rd1/K+BA2VWlndQ3hBc4Z3BnHtIMrJbu1mER7BG1REzDwC5MvCq/MOXf+qOpio+qMmMWZ6Tv77mtB0FGamxez3l4UxBvQIqv89nR+MEWWI9McNjNVp8aXQ6iV8iwUPxSELqapOoUcW+qb7VqAi4VjT+xbcwYtkrq045V+Fmui/6hATbEKs1T3627LEsIdA1cd3IBz8qu9yoo7ZH4oQiXxlSjpFI22HfZ46Tzhj5bkeYSfxoQ7TWaEpoislr1rTS6gDHw44Q/NYJlAgkK7aw82zIYGgreU+m5VqCvQWDrOMinSv61/UG2FvseM2tPT1mHoEy2lVTkNAgwMR+Vv1duTK6Fdd5P9qjJ/nAn8UBNYXWNyAPQet4xerPnYtlpLZXndMQ4a14Xhw9HpDgI+uR8v2xIVQgRgoOpIHskkY4VbxQXiydYmCxQr108n2gp8u2LBXGE2CI0m8kRyQQGc2ka3mHq8DtQFjoGVAg==
    client_secret: AgDSnf92crFuXHwF+UuWLbLLcMlkyQ84Vigt2biRuSZ3s1F2r0c0Ss05MClxtFDIXn+JZTHOYFUR3AN7rUWvHC+qAZwdAOn6Feew8J60d/6URbqvOSVcOqgzCduIj6xrFpapepktd+rfw3WTy0YW2pQE5lou01KGvWaet/kJwJA9RDTGQZzdAPDbmxVH6q7eL6b5ETOvn6vGpa5NUG8oY2KSEmRWKodwVDBTS6ZeD03ZxQBqubt8e3SJp0ghLTBIPJqKuQcrtgCw3YLET6CevtFKCKGvD4pJga14svefZtoBy6ILJ0Cn7QbR9bh4v5njDjTqCOOpAZcWRpvMz4iMfytzQVeJidChgL+vPBjKL/KDtwuroqlyBjruO1nqCBg7+fTO+fFL24/EJ453UWXWTMxVv7XnnAkWmdvHIcz27hk2Ml1T77h149UlNTw48LERhfU86cYzo1BkaYrsJR3SUOol9CCp1N/exrWfpPykYXS3j9wVfp/+jj8Pze8ATPWCshTN6QNXQz/BZYk2KvSJTsV5q1jwtilw2Jge+2TdHXWFSiGIbQOkNT4JAdu/eZrGxX2F5mYuWifqSIjfXKgHTBJmrgq1Nu8tHPgqWXl7vlAb+KzMlI2RgldMFARhYWkVcxvnP68Xk3HQxPZR/vU6myRlFF+5bSqWnlo7+clKP65WVNov5AJhuHosA5yAlrp7eF3TDvnK5PT4LxM/GHj4zHti51zW0H5Jx/Pqe049j0CJIUMxVmCrNQW4DY2uOtmcsD/YP3mqbV1zpEjnLYJ9ITM=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
